apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: AdpcA6211
  user: dbadmin

---
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
type: Opaque
data:
  username: c2Eud2ViYXBwLnNoYXJlCg==
  password: U3VwZXJTZWNyZXQxMjM0IQo=
  domain: dGVzdGRvbWFpbi5sb2NhbAo=

