apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-integration
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: Vol1
    volumeAttributes:
      source: "//192.168.5.131/Webapp$"
    nodeStageSecretRef:
      name: smbcreds
      namespace: webapp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-integration-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: smb-integration
  storageClassName: ""
